"""Add new fields to form submissions

Revision ID: 268141c5ae91
Revises: 0a0561a67ce3
Create Date: 2025-01-30 07:22:11.970586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268141c5ae91'
down_revision = '0a0561a67ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('referral_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('course_interest', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_column('course_interest')
        batch_op.drop_column('referral_source')
        batch_op.drop_column('country_code')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
