"""Add notes field to form submissions

Revision ID: 64be6422aad9
Revises: dc47399152cb
Create Date: 2025-01-30 08:06:37.618017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64be6422aad9'
down_revision = 'dc47399152cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
