"""Add phone and country_code to form submissions

Revision ID: dc47399152cb
Revises: 268141c5ae91
Create Date: 2025-01-30 07:52:13.776429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc47399152cb'
down_revision = '268141c5ae91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_column('course_interest')
        batch_op.drop_column('referral_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_source', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('course_interest', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
